import React, { useContext } from 'react';
import { View, ScrollView, StyleSheet } from 'react-native';
import { Appbar, Card, Divider, Text, Button } from 'react-native-paper';
import { GenerateVoucherPDF } from './voucherGenerator';
import { LoaderContext } from '../../context/LoaderContext';

export default function VoucherPreview({ route, navigation }) {
  const { expense } = route.params;
  const { showLoader, hideLoader } = useContext(LoaderContext);

  const handleDownload = async () => {
    try {
      showLoader();
      await GenerateVoucherPDF(expense, { showLoader, hideLoader });
    } finally {
      hideLoader();
    }
  };

  const formatDate = (dateStr) => {
    if (!dateStr) return '-';
    const d = new Date(dateStr);
    return `${d.getDate().toString().padStart(2, '0')}-${d.toLocaleString('en-US', { month: 'short' })}-${d.getFullYear()}`;
  };

  const firstNumberMatch = expense.expenseId?.match(/\d+/);
  const voucherIdNumber = firstNumberMatch ? firstNumberMatch[0].slice(0, 2) : '00';
  const voucherId = `E-voucher-${voucherIdNumber}`;


  return (
    <>
      <Appbar.Header>
        <Appbar.BackAction onPress={() => navigation.goBack()} />
        <Appbar.Content title="Voucher Preview" />
        <Button
          mode="contained"
          onPress={handleDownload}
          style={styles.downloadBtn}
          labelStyle={{ color: 'white', fontWeight: 'bold' }}
        >
          Download
        </Button>
      </Appbar.Header>

      <ScrollView style={styles.container}>
        <Card style={styles.card}>
          <Card.Title title="Tidy Digital Solution Pvt" subtitle={voucherId} titleStyle={styles.brand} />
          <Divider />

          <View style={styles.row}>
            <Text style={styles.label}>Expense ID</Text>
            <Text style={styles.value}>{expense.expenseId || '-'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Name</Text>
            <Text style={styles.value}>{expense.name || '-'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Invoice</Text>
            <Text style={styles.value}>{expense.invoice || '-'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Amount</Text>
            <Text style={styles.value}>₹{expense.amount || '0'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Category</Text>
            <Text style={styles.value}>{expense.category || '-'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Date</Text>
            <Text style={styles.value}>{formatDate(expense.date)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>GST</Text>
            <Text style={styles.value}>{expense.gst || '-'}</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.label}>Status</Text>
            <Text style={styles.value}>{expense.status || '-'}</Text>
          </View>

          <Divider style={{ marginVertical: 10 }} />
          <Text style={styles.sectionTitle}>Description</Text>
          <Text>{expense.description || '-'}</Text>

          <Divider style={{ marginVertical: 10 }} />
          <Text style={styles.footer}>
            Generated by Tidy Expense Tracker — {new Date().toLocaleString()}
          </Text>
        </Card>
      </ScrollView>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#f5f5f5',
    padding: 10
  },
  card: {
    padding: 10,
    borderRadius: 12
  },
  brand: {
    fontWeight: 'bold',
    color: '#5312A6',
    fontSize: 20
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  label: {
    color: '#555',
    fontWeight: '600'
  },
  value: {
    color: '#000',
    fontWeight: '700'
  },
  sectionTitle: {
    fontWeight: 'bold',
    marginBottom: 4
  },
  footer: {
    fontSize: 12,
    color: '#777',
    textAlign: 'center',
    marginTop: 10
  },
  downloadBtn: {
    backgroundColor: '#5312A6',
    marginRight: 10
  },
});
